Repository FoodieZone/Frontend, pull requests merged in 2023-09, with the labels that each got.

#10 [FE-16] feat: Icon 컴포넌트 png 지원확장
  package.json
  src/components/shared/Icon/index.tsx
  yarn.lock
Labels: feature

#6 [FE-12] feat: 월드컵 결과 페이지 퍼블리싱
  src/pages/Home.tsx
  src/pages/Home/index.consts.ts
  src/pages/Home/index.tsx
  src/pages/Home/index.types.ts
  src/pages/WorldCupResult/index.tsx
  src/pages/WorldCupResult/index.types.ts
  src/pages/index.ts
  src/routes/index.tsx
Labels: publishing

#8 [FE-14] feat: 결과 페이지 라우팅 생성
  src/App.tsx
  src/constants/index.ts
  src/constants/url.ts
  src/pages/WorldCupResult.tsx
  src/routes/index.tsx
Labels: feature, refactor
